### ISSUE TITLE
How do we localise plugins ?

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/conforma-web-app#455]
Do we envision more then one language for the same template ?

I think the simplest way would be to have all of the string in parameters. Otherwise we would need by plugin localisation

**Comment by CarlosNZ** [comment]
Parameters doesn't seem like a good place for it, because you'd have to define the language strings for EVERY instance of a plugin everywhere it's used. That's an awful lot of duplicated boilerplate and is just going to detract from what parameters are for, which is customizing specific instances of a plug-in, not just for values that are mostly going to be the same throughout the whole system.

Yes, I know you could have "defaults" in English, so you don't have to type them everywhere, but that's making a lot of work for non-English installations.

Not sure where the best place to store them is (we haven't really determined exactly how localisation is going to work for the main app), but any solution needs to ensure that language strings only need to be typed ONCE for each plugin type per system.

I don't see the problem with having separate localization for each plugin. You would expect that when someone writes a new plugin, they'd write it for their own language, then others would translate it as they install it on their systems. I just checked and that's how it is for Firefox, for example -- if I switch the language, most of the UI changes to the other language, but not all extensions have translations, only the ones where people have bothered to translate -- it's a case-by-case basis.

**Comment by CarlosNZ** [comment]
> Do we envision more then one language for the same template ?

Possibly, although templates can be translated as a whole -- there's pros and cons to each approach. But templates have "custom" strings -- i.e. every instance of an element has their own values (label, description, etc.), whereas "plugins" have a limited set of fixed strings (error messages, button text, etc.) -- they shouldn't change between instances, only for each system/language. We definitely shouldn't mix-and-match these two distinct groups of values.

**Comment by andreievg** [comment]
Ok I am convinced, we should have a strategy to localise plugins, sorry for digression with the parameters idea.

**Comment by CarlosNZ** [comment]
I think this is done. Each plugin has its own localisation files, which are and a "translate" method is provided by the LanguageProvider to all plugins.
