### ISSUE TITLE
Bug fix - when fileUpload isRequired but has only uploaded files not accepted (showing in red) it is considered as valid

### ISSUE THREAD

**Issue by nmadruga** [msupply-foundation/conforma-web-app#577]
part of one of the layout issue: #431

**Comment by CarlosNZ** [comment]
I think it will be easiest to do this while doing the other visual improvements to the plugin, since they'll both require a slight re-structure of the array of "file" objects -- but it'll be the same change for both. In other words, when we do the visual improvements (including progress bars), this bug should get taken care of automatically.
